### ISSUE TITLE
Error: not able to run your script, or run `apt update` on Proxmox

### ISSUE THREAD

**Issue by omariosouto** [luchina-gabriel/OSX-PROXMOX#1]
Your script doesn't run and doesn't give any feedback

I'm getting this error, do you have any suggestions?

- ![image](https://user-images.githubusercontent.com/13791385/140326389-39abac03-6a8a-44ac-9df4-8321a8f2fb18.png)

- ![image](https://user-images.githubusercontent.com/13791385/140326578-745ac465-4dab-4949-aded-c05844fea8fc.png)

**Comment by luchina-gabriel** [comment]
Please change sources.list repositories to other mirrors such as USA mirrors. 

Mirrors from Brazil are experiencing problems on last days.

thks
