### ISSUE TITLE
Issue Downloading Images

### ISSUE THREAD

**Issue by Murmur2k** [luchina-gabriel/OSX-PROXMOX#10]
Hi, having issues with the script, it seems to fail downloading the recovery (can be any of them) always at the same stage:

recovery-monterey.iso fails at 838.86mb (see it at this size in the ISO list)

“Creating virtual machine with macOS - Monterey ...
sed: can't read /etc/pve/qemu-server/100.conf: No such file or directory
Virtual machine created successfully.”

Any help appreciated, valeu!

**Comment by luchina-gabriel** [comment]
Hi,

Unfortunately there seem to be problems on Apple's servers to download the images. I notice that this always happens with dates close to the release of macOS versions (perhaps some kind of overload).

It is necessary to try until you succeed.

After each attempt, it checks whether the recovery creation log and which is inside /root/OSX-PROXMOX/logs show failures.

Regards,
Gabriel

**Comment by Murmur2k** [comment]
Got it working, thanks!
