### ISSUE TITLE
iphone and xcode 

### ISSUE THREAD

**Issue by Abdelkader-gnichi** [luchina-gabriel/OSX-PROXMOX#12]
hi please did it recognize the iphone from usb because i'am a developer and i want to use iphone and xcode to build some ios app please answer me and thank u nice job

**Comment by luchina-gabriel** [comment]
Hi, in my setup iphone and other devices, included xcode, works normally. I believe that you have other problems in your setup.

What version of macOS you use?

**Comment by Abdelkader-gnichi** [comment]
Hi and I'm so thankful for ur answer truly i mean it so i don't use ur solution yet which is a good one and i believe in virtualisation and i still don't try it honestly because i'am worry i try to install macos with a package named sosumi it's a snap package allow u to install macos with qemu vm but can't make it recognise it stuck with it 3 days i google the issue and try every solution that found it but nothing so delete and i find ur solution and i want to make sure that it will be work with my hardware and really it like me and i think to remove everything from my pc and build a small proxmox lab contain fedora and macos but as i told u i want to be sure that it tested with hardware like my hardware first and i find on the internet that even with proxmox there is a problem with the igpu so please can u confirm it to me that ur solution will work with my hardware or not i have a lenovo thinkpad T460s with igpu intel HD graphics 520 so please confirm it to me and again thank a lot

**Comment by clederperufo** [comment]
Olá Gabriel, parabéns pela iniciativa achei show de bola esse sistema de virtualização.
Estou seguindo o passo a passo do youtube e estava dando tudo certo até a parte do start (qm start 100) onde retornou um erro e não consegui mais acessar a maquina virtual pois da o seguinte erro (Failed to connect to server).
Porém o ping esta normal

**Comment by luchina-gabriel** [comment]
> Olá Gabriel, parabéns pela iniciativa achei show de bola esse sistema de virtualização. Estou seguindo o passo a passo do youtube e estava dando tudo certo até a parte do start (qm start 100) onde retornou um erro e não consegui mais acessar a maquina virtual pois da o seguinte erro (Failed to connect to server). Porém o ping esta normal

Oi, obrigado pelo feedback! Acessa o nosso [DISCORD](http://discord.universohackintosh.com.br/) lá consigo te ajudar mais certinho a respeito.

**Comment by Abdelkader-gnichi** [comment]
> Hi, in my setup iphone and other devices, included xcode, works normally. I believe that you have other problems in your setup.
> 
> What version of macOS you use?

I have a laptop lenovo thinkpad t460s
