### ISSUE TITLE
Código fonte do arquivo de setup

### ISSUE THREAD

**Issue by RodriguesCosta** [luchina-gabriel/OSX-PROXMOX#13]
Primeiramente gostaria de parabenizar pelo excelente trabalho, porem gostaria de tirar uma dúvida, onde esta o código fonte do arquivo de setup? manter ele no repositório ajudaria ao projeto crescer, pois, mais pessoas poderiam adicionar funcionalidades e recursos.

**Comment by luchina-gabriel** [comment]
Oi Rodrigues, obrigado pelo feedback! Estou ciente dos ganhos de tornar o código fonte disponível, mas no momento o mesmo ainda é mantido proprietário por mim, planejo em um futuro breve tornar o projeto opensource.

Abs,
Gabriel
