### ISSUE TITLE
Only shows "Reset NVRAM"

### ISSUE THREAD

**Issue by aporzio1** [luchina-gabriel/OSX-PROXMOX#15]
I run the `osx-setup` command and everything runs fine. When I boot the VM it takes me to the drive selection page but the only option is "Reset NVRAM. I tested with High Sierra, Big Sur and Monterey and they all do the same thing. 

![Screen Shot 2022-01-02 at 5 28 16 PM](https://user-images.githubusercontent.com/7033289/147891055-e7c56145-fa0f-40b2-b8e9-5a6404cd299a.png)

![Screen Shot 2022-01-02 at 5 29 27 PM](https://user-images.githubusercontent.com/7033289/147891073-733b2f59-f8f8-4a06-92b9-46889c12a4d9.png)

**Comment by luchina-gabriel** [comment]
Hi,

macrecovery fails to download and create a recovery image.

Try again, but before execute this process:

`rm -f /var/lib/vz/template/iso/recovery*.iso`

and try again: `osx-setup`.

A few days, unfortunately, mac recovery images occurring problems :(

Cheers ;)
