### ISSUE TITLE
Script failed to create the VM

### ISSUE THREAD

**Issue by intelliop76** [luchina-gabriel/OSX-PROXMOX#19]
macOS Monterey
 
Enter a disk size [INTEGER] [Default: 64 Gb]: 
Do you want to download and create the recovery image? [Y/N] [Default: Y]: 
 
Downloading and creating the recovery image for installation ...
Recovery image of macOS Monterey already exists.
 
Creating virtual machine with macOS - Monterey ...
sed: can't read /etc/pve/qemu-server/101.conf: No such file or directory
Virtual machine created successfully.
 
Access the Proxmox Web Panel to continue with the installation ...
https://192.168.80.2:8006

**Comment by ietwat** [comment]
same here..

**Comment by luchina-gabriel** [comment]
Storage 'local-lvm' are necessary.
