### ISSUE TITLE
Tem script pra Virtual Environment 7.0-13?

### ISSUE THREAD

**Issue by cbuosi** [luchina-gabriel/OSX-PROXMOX#2]
"This version of Proxmox Virtual Environment are not supported
Please, utilize version: 7.0-11"

**Comment by luchina-gabriel** [comment]
Hi Carlos,

I'm doing the approval of this version, although it is not the stable version considered by the Proxmox team and I should release updates in the next few days including support for it.

Regards,
Gabriel
