### ISSUE TITLE
VM won't progress past the UEFI screen

### ISSUE THREAD

**Issue by big-harry** [luchina-gabriel/OSX-PROXMOX#20]
Whenever I try to boot, regardless of the version of MacOS I download, it won't boot into it. It gets stuck trying to boot into the image. I waited for over 20 minutes for it to still be stuck on this.

![Frozen BIOS](https://user-images.githubusercontent.com/94585779/148667298-539995bc-1808-448e-945e-8bdd38c1a6b5.png "Doesn't progress past here")

All my other machines work fine, just not these MacOS machines.

I am running this on a Dell PowerEdge 720 with 24 CPUs and 16 GB of RAM.

**Comment by luchina-gabriel** [comment]
Configure total of CPUs for power of 2. eg: 2, 4, 8, 16, 32...

Check if VT-d and VT-x in your BIOS are Enabled.

Check if create a Windows VM, boot ocurring normally, please.

**Comment by mava70** [comment]
I have the same problem VT-d and VT-x enabled windows boot regurarly

**Comment by big-harry** [comment]
I've had it configured for 4 cores and 1 socket. VT-d and VT-x are enabled. Both my Ubuntu VM and my Windows XP VM work without issue.

**Comment by big-harry** [comment]
Here's my configuration, it's the default one from the script

![Image showing configuration for a MacOS virtual machine](https://user-images.githubusercontent.com/94585779/148867971-b91c1322-b656-4cb3-9b3b-503223ad7458.png)

**Comment by big-harry** [comment]
I've also tried booting manually into the EFI file, but that didn't work either

**Comment by mava70** [comment]
I tryed different things, redownloaded different macos version, changed disk options, manually download opencore iso, the problem rely in my opinion in the opencore iso, because if I remove this disk  I can boot in the efi command prompt

**Comment by mava70** [comment]
I solved the problem with a workaround for some reason the images will be downloaded incompletely Monterey is only one gig, and opencore 40g also by redownloading multiple time the problem is till there, if I reupload the image built following this guide: https://www.nicksherlock.com/2021/10/installing-macos-12-monterey-on-proxmox-7/ the boot process go on I am just installing monterey now.

**Comment by big-harry** [comment]
For me all recovery images are 801MB and the OpenCore image is 55MB. I'll see if I can get it to work with your workaround.

**Comment by big-harry** [comment]
Using the latest version didn't fix it

**Comment by luchina-gabriel** [comment]
remove all usb devices, and tray again. Check your bios settings (vt-d and vt-x are necessary)

**Comment by big-harry** [comment]
I have, still nothing

**Comment by TheBrokenG0d** [comment]
Same issue aswell
