### ISSUE TITLE
GPU Passthrough

### ISSUE THREAD

**Issue by mnitpro** [luchina-gabriel/OSX-PROXMOX#22]
Hi,

I followed the instructions, and you made it pretty easy to have macOS Monterey up and running. However, I noticed the graphics is just 7MB, while I have onboard integrated GPU of 128MB on my Dell XPS 13 9310 i7-11875g. I tried VMware compatible, SPICE and VirtIO GPU, and the system is still sluggish. Is there any solution for that? Can I have a bare minimum of at least 64MB to perform well?

Other point is that I want to set a custom screen resolution to fit my diagonal 13.3" inch, I used to do that on the vmx file in VMware, is there an alternate option here in proxmox?

Thanks a lot man for making all of these efforts.

**Comment by luchina-gabriel** [comment]
Hi mnitpro,

iGPU are not supported by passthrough in proxmox officially.

Try this project:
https://github.com/patmagauran/i915ovmfPkg

Maybe work, but testing are necessary! 

Thanks for your feedback! ;)
