### ISSUE TITLE
Computer Stuck in "Loading Linux 5.11.22-4-pve... Loading Initial ramdisk ..."  - Installation Successfull on remote access

### ISSUE THREAD

**Issue by omariosouto** [luchina-gabriel/OSX-PROXMOX#4]
Hi, I can access remote as normal, but I'm receiving this "error" in the computer after only run the script and install the Monterrey macOS. Is it normal/expected?

![image](https://user-images.githubusercontent.com/13791385/140604367-5e988db2-9e27-4631-a1c8-408de84602ab.png)

![image](https://user-images.githubusercontent.com/13791385/140604296-7f4ff5e3-c77c-48fe-b306-0e45271b3057.png)

**Comment by luchina-gabriel** [comment]
Hi Mario :)

it's not a problem, it's ocurring because osx-setup apply settings for easily GPU Passthrough in future moment.

Regards,
Gabriel
