### ISSUE TITLE
Not creating the VM

### ISSUE THREAD

**Issue by Moerbius** [luchina-gabriel/OSX-PROXMOX#5]
Hi

Using proxmox 7.0.13 the script downloads the necessary isos but it does not create the VM.

**Comment by luchina-gabriel** [comment]
Hi Isaias,

Please execute this command and send me URL generated after execution:

```
for i in `ls /root/OSX-PROXMOX/logs/`; do echo "FILE: $i"; cat /root/OSX-PROXMOX/logs/$i; echo -e "--------------------------------------------------- \n \n \n \n"; done | nc termbin.com 9999
```

Regards,
Gabriel

**Comment by Moerbius** [comment]
Hello Gabriel,

It gave the following:
`https://termbin.com/p8gg`

Best regards

**Comment by luchina-gabriel** [comment]
Hi Isaias,

Exactly, I saw this error in the log.

OSX-PROXMOX is `hardcoded` for storage usage, I'll adjust this in future releases, but for now it only uses `local-lvm` by default.

Create new storage with name `local-lvm` and that works, but I include this "feature" of choose storage name in next versions.

Regards,
Gabriel

**Comment by roobandev** [comment]
I am having the same issue as my storage name is local-zfs. Upvoting for this feature.
