### ISSUE TITLE
Erro ao executar o comando /bin/bash -c "$(curl -fsSL https://install.osx-proxmox.com)"

### ISSUE THREAD

**Issue by pcbelem** [luchina-gabriel/OSX-PROXMOX#6]
Após executar o comando /bin/bash -c "$(curl -fsSL https://install.osx-proxmox.com)", apareceu o erro: /bin/bash: line 44: /root/OSX-PROXMOX/setup: No such file or directory.
Fui na pasta /root/OSX-PROXMOX/ e de fato está vazia.

**Comment by luchina-gabriel** [comment]
Executa novamente, as vezes está dando falha na hora de clonar o repositório (internet).

**Comment by pcbelem** [comment]
Abri o script e tentei instalar o git e executar o OSX-PROXMOX.git. Mas após sua orientação, executei novamente e deu certo. Agora seguirei para os próximos passos. Obrigado.

**Comment by luchina-gabriel** [comment]
Show de bola! 🚀
