### ISSUE TITLE
Interesting project :grinning: Few issues I noticed, plus some suggestions about improving user interaction and trust

### ISSUE THREAD

**Issue by Viveur** [luchina-gabriel/OSX-PROXMOX#7]
Nice work creating this :partying_face: 

Feel fortunate to have found it so soon after the initial release!

Seems like a fun project, but also one people would find useful :cake: 

I can see things are still in their early stages; however, there are a few issues that immediately rung serious alarm bells for me...

- The main 'setup' file is a binary. It doesn't seem that any source code has been posted?! 
- It is bad form to automatically reboot a system with only a brief warning before. This it doubly problematic for Proxmox where people may have VM's/containers they want to keep online. 
- There is very little information given to the user explaining what actions are happening/taken. 

Unfortunately these issues make the project seem pretty shady! The reboot alone makes it seem like it is trying to install a virus/rootkit; however, to not be able to view the source code, when the project itself is posted on Github, was a major concern! :fearful: 

Here's some advice and various things I spotted that seemed odd that I hope you find helpful:

- Posting the code would let users verify and review what is happening to their system, which is important for a project like this. 
- Sharing it with others would also mean people could contribute and fix :lady_beetle:'s too 
- Let the user make a choice when there are parameters that can be changed, such as: ram, number of cores, and storage of the VM.
- Print the output of each command to the screen.
- Rework setup so that a reboot is not necessary. If a reboot is essential then explain why.
- Consider adding some text that explains the detail of what will happen _before_ proceeding. Most people running Proxmox are technical and would be interested in how it works. Perhaps think of it like a guided tutorial :mortar_board: 
- It's definitely not necessary to add `alias osx-setup='/root/OSX-PROXMOX/setup` into a users .bashrc file.
- Ask before changing the source.list: `sed -i 's/ftp.br.debian.org/ftp.debian.org/g' /etc/apt/sources.list`
- And especially ask before deleting a source.list: `rm -rf /etc/apt/sources.list.d/pve-enterprise.list` -- there might be a minority of people that need this, in which case you just broke their system!

Ps. I tried to get this up and running, but hit some problems. It seems the software currently makes too many assumptions. Other than checking the logs (which appear incomplete), it's kinda impossible to figure out what's going on (or what changes are being made to my system!) at the moment.

:boom:

**Comment by luchina-gabriel** [comment]
Thanks for the feedback!

And the project's initial idea is to take macOS to people who do an initial PVE installation as I demonstrate in my YT video, so it does everything automatically, precisely because in the scenario I'm introducing it, people generally don't know the product and know very little about virtualization and everything else.

I agree with everything that was sent as suggestions, but as the audience is different, the approach I used was this for now, and I have some "competitors" who have been shamelessly copying my videos on the platform, which is why it is binary, just to avoid copying, i plan to open the project in the future.
